Repository workato/connector_sdk, pull requests merged in 2018-07, with the labels that each got.

#126 Marketo SDK
  custom_auth/Marketo.rb
Labels: S3-code review

#122 Calendly SDK Connector
  api_key_auth/Calendly.rb
Labels: S2-testing

#120 Typeform Connector SDK
  oauth2/Typeform.rb
Labels: S3-code review

#121 Harvest SDK Connector - Initial Commit
  oauth2/Harvest.rb
Labels: S3-code review

#128 BMC Innovation Suite - SDK adapter
  custom_auth/bmc_innovation_suite_connector.rb
Labels: S3-code review

#98 Paypal Adapter
  custom_auth/paypal.rb
Labels: S1-development

#129 Facebook (custom) - SDK adapter
  api_key_auth/facebook_connector.rb
Labels: S3-code review

#130 Action Network - SDK adapter
  api_key_auth/action_network_connector.rb
Labels: S3-code review

#134 Google Bigquery - SDK adapter
  oauth2/google_bigquery_connector.rb
Labels: S3-code review

#133 Sage Intacct (custom) - SDK adapter
  custom_auth/sage_intacct_connector.rb
Labels: S3-code review
